# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "Rileysoft.ShiftJIS/Rileysoft.ShiftJIS"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies: "
  - package-ecosystem: "nuget"
    directory: "Rileysoft.ShiftJIS/Rileysoft.ShiftJIS.Tests"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies: "
